### ISSUE TITLE
plug crashes with gnome-settings-daemon 3.34 (removed GSettings key)

### ISSUE THREAD

**Issue by decathorpe** [elementary/switchboard-plug-mouse-touchpad#122]
Looks like GNOME people monkey'd around with gnome-settings-daemon 3.34 *again* (**sigh**), and removed or renamed the `locate-pointer` key from GSettings:

`
io.elementary.switchboard:7969): GLib-GIO-ERROR **: 13:45:12.561: Settings schema 'org.gnome.settings-daemon.peripherals.mouse' does not contain a key named 'locate-pointer'
`

This leads to a crash when opening the Mouse & Touchpad plug.

Any idea how to resolve this issue? Conditional compilation for g-s-d >= 3.34? I mean, ubuntu 20.04 LTS will have this change too, I guess ... unless they do compatibility downstream patches again

**Comment by danrabbit** [comment]
Looks like the plugin was removed because it moved to the compositor for Wayland: https://github.com/GNOME/gnome-settings-daemon/commit/6dff93a0dfa80db3f481eed5d6ed689bf469aa1b

So we should probably check for the existence of the key and not show the setting if it doesn't exists.

Submitted an issue for Gala here: https://github.com/elementary/gala/issues/665
