### ISSUE TITLE
Settings for multi-touch gestures

### ISSUE THREAD

**Issue by danielnd14** [elementary/switchboard-plug-mouse-touchpad#16]
The Switchboard-Plug-Mouse-Touchpad could support predefined gestures created by the elementary OS team, this could enhance the user experience.
I proposed basic gestures such as:

1. A gesture to switch from desktop, could be using 3 fingers sliding them to left or right.

2. Show the Multitasking View (the same result that you would get when pressing the command ⌘+S), the gesture could be using 3 fingers and moving them upwards.

3. Show all open apps (the same result that you would get when pressing the command ⌘+A), the gesture could be using 3 fingers and moving them downwards.

4. Zooming in or out by making a pincer movement.

PS: It is important that there is a option to turn off said gestures in the system configurations, the user might prefer to have them disabled.

**Comment by donadigo** [comment]
Looks like we should use something like (libinput-gestures)[https://github.com/bulletmark/libinput-gestures] for this.

**Comment by marcelogdeandrade** [comment]
I will try to do this.

What's your opinion on using [this](https://valadoc.org/gtk+-3.0/Gtk.Gesture.html) lib?

**Comment by marcelogdeandrade** [comment]
If I use libinput-gestures, it should be a default package on elementary right? Where is the right place to make this change so it should be a default system package?

**Comment by codygarver** [comment]
@marcelogdeandrade if you get it working with something that's not already a default package and the code is approved, I will do the rest and make it available.

**Comment by codygarver** [comment]
Using a library already in the repos would be preferable, but I am not familiar with this situation so maybe `libinput-gestures` is appropriate if others agree.

**Comment by marcelogdeandrade** [comment]
Ok, thanks for the help, I'll work on this issue

**Comment by marcelogdeandrade** [comment]
I'm finishing my first implementation, just one question:

Do you prefer to have predetermined shortcuts to swipe gestures or to receive any shortcut from the user?

If the answer is predetermined shortcuts, which ones?

Thanks

**Comment by peteruithoven** [comment]
I'm not sure I understand the question, but shouldn't this be configurable, just like Keyboard shortcuts?

**Comment by danrabbit** [comment]
I don't think `libinput-gestures` is the route to pursue here. What we really want is to implement native 1:1 gestures in Gala, not gesture shortcuts that activate after the fact. This issue is effectively blocked by Wayland.

**Comment by marcelogdeandrade** [comment]
Oh, that's too bad, I had just finished my implementation with `libinput-gestures` :confused:.

 Anyways, I'll create an PR based on what @donadigo and @codygarver said and you can see if there's anything that can be used in the future :smiley:

**Comment by cassidyjames** [comment]
My opinion is that while 1:1 is obviously preferred, `libinput-gestures` is a minimal step in the right direction and does feel **much** better than having nothing at all. That said, I don't think per-swipe configuration is really something we'd want; instead, I'd expect to see something like this in the UI:

```
Multi-touch gestures: (--o) (i)
____________________________/\__________________________
|                                                      |
|  Four-finger swipe left/right to switch workspaces.  |
|  Four-finger swipe up for Multitasking View.         |
|______________________________________________________|
```

And then we could manage whether switching right/left is inverted based on the scroll direction key, so it always matches other scrolling on the device.

If a user wants fine-grained control over gestures, they can edit the config or install a dedicated tool like Gestures to do so.

**Comment by cassidyjames** [comment]
Also to note: it sounds like GNOME is standardizing on four fingers for OS/Shell-level gestures, and I think we should as well. That allows apps to have three-finger gestures where it makes sense, and I don't want to conflict with that expectation too much. I believe macOS makes a similar assumption.

**Comment by marcelogdeandrade** [comment]
@cassidyjames I believe this implementation with a fixed behaviour is much simpler than the one I did, if  you guys decide that using `libinput-gestures` is ok for now, I can change it to the UI you proposed.

**Comment by peteruithoven** [comment]
If we want to define a predefined list I'd recommend doing some research on how other OS's handle multi touch, maybe create a short overview. See is there is common ground.

**Comment by cassidyjames** [comment]
macOS and GNOME use four-finger swipes to switch workspaces. I am not sure about Windows. macOS uses a four-finger swipe up to bring up the multitasking view. I believe those all make sense here, especially since we already have two-finger swiping between workspaces in the Multitasking View. So this would just be an extension of that without having to jump into that view with the mouse or keyboard first.

**Comment by danrabbit** [comment]
It looks like macOS offers individuals toggles for each gesture and the ability to change the gesture for each function. I think having toggles for each gesture makes sense rather than all or nothing. 

![customise-macos-default-trackpad-gestures](https://user-images.githubusercontent.com/7277719/46989744-18499900-d0b3-11e8-9581-288b131de398.png)

**Comment by peteruithoven** [comment]
Why not reuse the same UI principle as custom Keyboard shortcuts? 
A first column with possible actions (possibly keyboard shortcuts), the second are the gestures. When clicking on the gesture you can record a new one. 
(and yeah should probably go into a new tab)

**Comment by AlonsoEnrique** [comment]
When will Wayland be ready for elementary os? wait for the next release of Ubuntu LTS for support gestures, two years more :/, bad decision. Fractional scaling Déjà vu :(.

**Comment by Akryum** [comment]
@cassidyjames Both MacOS and Windows 10 use a 3 fingers gesture for worskpace switching and windows overview. I'm not sure if four-finger is intuitive enough for new users, especially if they come from those OSes.

**Comment by cassidyjames** [comment]
@Akryum macOS uses four fingers. https://support.apple.com/en-us/HT204895

**Comment by cassidyjames** [comment]
@Akryum Windows 10 also uses four fingers for workspaces. https://support.microsoft.com/en-us/help/4027871/windows-10-touchpad-gestures

**Comment by Akryum** [comment]
@cassidyjames The 2017 macbook pro I had was 3 fingers but ok. 😸

**Comment by psafarov** [comment]
```vala
int main (string[] args)
{
    var udev = new Udev.Udev();
    var interface = Libinput.Interface() {
        open_restricted = (path, flags) => Posix.open(path, flags),
        close_restricted = (fd) => Posix.close(fd)
    };
    var context = Libinput.Context.udev_create_context(interface, null, udev);
    context.udev_assign_seat("seat0");

    while (true) {
        context.dispatch();

        Libinput.Event? event;
        unowned Libinput.Event.Gesture? gesture;
        while ((event = context.get_event()) != null) {
            switch (event.get_type()) {
                case GESTURE_SWIPE_BEGIN:
                case GESTURE_SWIPE_UPDATE:
                case GESTURE_SWIPE_END:
                    if ((gesture = event.get_gesture_event()) != null) {
                        stdout.printf("Gesture swipe with %d fingers\n", gesture.get_finger_count());
                    }
                    break;
                default:
                    print(event.get_type().to_string() + "\n");
                    break;
            }
            context.dispatch();
        }
    }

    return 0;
}
```

It is relatively easy get swipe gestures from `libinput`. I am not familiar very well with gala myself, unfortunately, to transform it into something useful.

**Comment by Exalm** [comment]
> @Akryum macOS uses four fingers. https://support.apple.com/en-us/HT204895

it's configurable between 3 or 4, though I don't know which one is default.

**Comment by ekvedaras** [comment]
> > @Akryum macOS uses four fingers. https://support.apple.com/en-us/HT204895
> 
> it's configurable between 3 or 4, though I don't know which one is default.
> 
> Edit: https://www.imore.com/sites/imore.com/files/styles/xlarge/public/field/image/2016/07/Trackpad-changes-swipe-full-screen-Mac-screenshot.jpg?itok=r4lGC5d3

Everytime I used a mac it was 3 fingers. Not even sure where to change it to 4.

**Comment by Exalm** [comment]
> Everytime I used a mac it was 3 fingers. Not even sure where to change it to 4.

System Preferences -> Trackpad -> the screenshots I linked to

**Comment by bumper314** [comment]
Just another data point, Chrome OS will be adding "virtual desks" (workspaces) in the forthcoming Chrome OS 78 release, with **3 finger** swipe being the gesture to switch between desktops.  [Source](https://chromeunboxed.com/chrome-os-78-virtual-desks-navigation-multi-finger-gesture/).

Personally, I prefer 4 finger, so that's my vote.

**Comment by linuxr01** [comment]
Elementary OS touch gestures tutorial https://www.youtube.com/watch?v=ArBCfhVsTZw.

**Comment by SephReed** [comment]
> Why not reuse the same UI principle as custom Keyboard shortcuts?
> A first column with possible actions (possibly keyboard shortcuts), the second are the gestures. When clicking on the gesture you can record a new one.

While recording might be difficult, allowing users to choose seems like the best way to.  Then you can enable it, disable, customize.  Also, not everybody has 4 fingers.  I know that's not super common, but can you imagine how shitty that would be?

Also, I know everyone thinks their issue is the most important, but I've been following EOS for about 3 years waiting for this feature.  Windows inability to make this feature work smoothly is one of the main reasons I find the OS unusable.  Then again, I haven't seen any other MacOS user who depends on desktops as much as I do... maybe it's just me.

**Comment by SephReed** [comment]
Also, the bounty on this is up to $170, if someone is able to update the title.

**Comment by Exalm** [comment]
Recording is impossible, I'll just say that.

The only blocker for just implementing gestures is Wayland, though that's a pretty huge one. :) Once Pantheon uses Wayland, implementing gestures would be easy. Until then, impossible.

**Comment by SephReed** [comment]
I searched around and found no road map for when wayland will make its way into EOS.  If anyone knows, please share.  I'd like to set a calendar reminder to come check out the OS again.  It's really come along these passed 3 years!

**Comment by Exalm** [comment]
I don't think there's a roadmap, but it's a _really_ huge change. And the largest part of the change is that most third-party apps will need changes (for example, saving and restoring window position and size, like they do now, is not possible in Wayland, so not only a replacement will need to be written, but apps will need to be ported), so it would also require a major version bump.

**Comment by marbetschar** [comment]
Until there's an official integration of Multi Touch Gestures, you might want to try [fusuma](https://github.com/iberianpig/fusuma). It works addictively well!

For autostarting, I simply added `fusuma` as custom command in **System Settings > Applications > Startup**

Here's the config I use for elementary OS:

```
$ cat .config/fusuma/config.yml 
swipe:
  3:
    left:
      command: 'xdotool key alt+Right'
    right:
      command: 'xdotool key alt+Left'
  4:
    left:
      command: 'xdotool key super+Right'
    right:
      command: 'xdotool key super+Left'
    up:
      command: 'xdotool key super+Down'
    down:
      command: 'xdotool key super+Down'
pinch:
  2:
    in:
      command: 'xdotool key ctrl+plus'
      threshold: 0.1
    out:
      command: 'xdotool key ctrl+minus'
      threshold: 0.1

threshold:
  swipe: 1
  pinch: 1

interval:
  swipe: 1
  pinch: 1
```

**Comment by SephReed** [comment]
Is there any reason this tool couldn't be included by default, with a bit of UI for setting it up?

**Comment by marbetschar** [comment]
@SephReed I expect this tool is not included because it is considered a hack and insecure. See the comment from Exalm earlier in this issue: https://github.com/elementary/switchboard-plug-mouse-touchpad/issues/16#issuecomment-552226823

**Comment by andirsun** [comment]
Maybe in the near future the elementary os team will do a gestures in the touchpad natively ?

> @SephReed I expect this tool is not included because it is considered a hack and insecure. See the comment from Exalm earlier in this issue: [#16 (comment)](https://github.com/elementary/switchboard-plug-mouse-touchpad/issues/16#issuecomment-552226823)

**Comment by SephReed** [comment]
This has legitimately been the biggest barrier to entry for me personally for a while.  I'm hardcore addicted to the gestures on MacOS and can not go for any extended period of time without them.

I can't use Windows for the same reason.

**Comment by danrabbit** [comment]
I've created a project to track multi-touch gestures inside apps: https://github.com/orgs/elementary/projects/61

**Comment by SephReed** [comment]
Lot of attention for touch pads in linux lately:  https://bill.harding.blog/2020/05/17/linux-touchpad-preliminary-project-funding-survey-results/

**Comment by Exalm** [comment]
That project is soo misguided. Libinput has supported gestures since forever, it's really XI2 and individual apps/Gala that are not supporting them. When you have Wayland and so not bound by XI2, gestures are perfectly possible and e.g. gnome-shell has some at this point.

Nevermind the "libinput sucks, we can do it better" approach. All of the non-gesture things there vary wildly depending on hardware and if something doesn't work on libinput well, it's likely because nobody has reported an issue (and it's impossible to test in every hardware on existence)

And of course the whole "Make Linux touchpad work as well as on MacBook" premise — a large part of that is hardware.

**Comment by JoseExposito** [comment]
Oh crap, I'm 6 days late to claim that $100 bounty... Such a bad timing :rofl: :rofl:  Just kidding :yum: 

I'm testing with 3 different designs, let me know which one you like the most or if you have something else in mind. You are much better than me on UX, so I'll really appreciate your advice.

In my opinion, moving "Gestures" to a different tab works quite well. It allows us to avoid overloading the "Touchpad" tab while allowing to add as many gestures as we want plus some info/help text in case we consider it is required.

An icon is required though... It is just better if I don't try to paint it, believe me :laughing: 

About the available gestures, I'll add: (personal opinion)
 - Multitasking view (swipe up with 3/4 fingers)
 - Change desktop (swipe left or right with 3/4 fingers)
 - Maximize window (swipe up with 3/4 fingers)
 - Tile/snap window (swipe left or right with 3/4 fingers)
 - Minimize/hide window (swipe down with 3/4 fingers)


Here are the mocks

 - Text + Combo Box: The combo box includes a "Disabled" option. Personally, I like this one the most. It looks like the "Scrolling" option in the "Touchpad" tab:
   ![only-combos](https://user-images.githubusercontent.com/1335948/99993056-72030e00-2db7-11eb-8ed1-1438387d11d9.png)

 - Text + Switch + Combo: It looks like the "Physical clicking" option in the "Touchpad" tab:
   ![with-switches](https://user-images.githubusercontent.com/1335948/99993077-77f8ef00-2db7-11eb-8d0e-7300bba5a1df.png)

 - Text + Switch + Combo in 2 lines: I feel like that the font size for the label should be a little bit bigger. I don't think this option is used somewhere else in the system settings, so -1 for inconsistency:
    ![two-lines](https://user-images.githubusercontent.com/1335948/99993092-7d563980-2db7-11eb-9881-fb2c92e938ba.png)

**Comment by cassidyjames** [comment]
@JoseExposito awesome! I personally like the text/switch/combo as it lets you quickly toggle settings on/off ideally without losing your previous selection. Also, a note: this should go under Behavior, not devices imho since it deals with gestures on both touch screens and trackpads. :wink: As for the icon, we will need to come up with something, but you could use `input-touchpad-gesture` or something as a placeholder for now which I think should fallback to the touchpad icon.

**Comment by danrabbit** [comment]
@JoseExposito if you wanted to open a draft PR that would be great :) I can work on an icon. This looks awesome though, I'm super excited how quickly this is all coming together. Great work! And yeah unfortunately we're not using Bountysource anymore, but maybe we can figure out some kind of compensation. I see you're on GitHub sponsors. I'll bring it up with the team :)

I agree with Cass that this probably makes more sense under "behavior" in the sidebar. And yes definitely agree that it makes sense as its own page separate from touchpad, especially since it effects touch screens as well.

Also agree that using a switch makes it easy to turn things off or on without losing your previous selection (which may be the default). I imagine for some folks they'll want to experiment a little until they find their right setup. The last option you showed fills up vertical space nicely, which if we only have a few options could be good. If we go with that one, we should double space between options so it's clear that the label, switch, and combo are all one group

As for which options, I agree with your selection with the exception of Minimize/Hide. We're really trying to de-emphasize minimize, especially since the shell doesn't really handle it well. Though we do still have "Hide" in keyboard shortcuts, so it's not a hill I'll die on :upside_down_face:. The options you have listed with directions and fingers make sense to me. To be consistent with the rest of the interfaces I think the strings should be:

* Multitasking View
* Switch Workspaces
* Maximize Window
* Tile Window

**Comment by JoseExposito** [comment]
Sure, here is the PR: https://github.com/elementary/switchboard-plug-mouse-touchpad/pull/157

It only contains a bare-bones UI with your suggestions, but it allows us to start working on it!
