### ISSUE TITLE
Add ability to turn off touchpad

### ISSUE THREAD

**Issue by VisioFX** [elementary/switchboard-plug-mouse-touchpad#18]
New feature request for Elementary OS Loki:

Would love to see and ability to turn off the touchpad completely with a button in the switchboard.

When I type something on the keyboard I always seem to accidentally touch the touchpad, so to me it is  completely useless and just an annoying feature that I always turn off in other operating systems.

**Comment by cassidyjames** [comment]
There is a setting at `org.gnome.desktop.peripherals.touchpad send-events` that _should_ work for this, but seems to be broken due to #19. 

But even if it worked, I'm not sure turning the trackpad off completely is a good idea, unless we provide a keyboard-friendly way to turn it back on; imagine the case where someone with _only_ a trackpad as a pointer device hits the toggle and now can't turn it back on.

There is also an option in Unity to "Disable touchpad while typing" which uses `syndaemon` under the hood; something similar might be a better approach, or we could see if LibInput has a way to do the same.

**Comment by Philosoft** [comment]
Guys. There is `syndaemon` for this already, which comes automagically with `xserver-xorg-input-synaptics` package. Just integrate it in this switchboard plugin. [Man page](https://linux.die.net/man/1/syndaemon) is pretty simple. Some reasonable defaults like `syndaemon -d -k -i 0.2` would be much appriciated by laptop-centric fellas like me.

@VisioFX just add `syndaemon -d -k -i 0.2` to your autostart settings and enjoy. With this, while you type touchpad will be disabled for 0.2s. Plus if you press modifier keys only (<kbd>alt</kbd>, <kbd>shift</kbd>, <kbd>ctrl</kbd>, <kbd>meta</kbd> and may be something else) touchpad would be working still.

**Comment by danrabbit** [comment]
There is now a setting to disable the touchpad when a mouse is connected. Ignore while typing is also turned on by default. I would say this is probably solved now
