### ISSUE TITLE
Mouse Pointer speed doesn't go high enough.

### ISSUE THREAD

**Issue by skewty** [elementary/switchboard-plug-mouse-touchpad#39]
**Mouse Pointer speed** doesn't go high enough.
Even at max, my trackball is too slow for my high resolution monitors.

**Comment by danrabbit** [comment]
This settings pane is just a front end for configuring settings in GNOME settings daemon. Setting mouse pointer speed to its maximum value here is the maximum value that GSD will accept. Closing as "Out of scope" since this problem can't be solved in this code base

You can try filing an issue against [GNOME settings daemon](https://gitlab.gnome.org/GNOME/gnome-settings-daemon).

**Comment by m93a** [comment]
As they say in [gnome-settings-daemon#139](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/issues/139), it's out of scope even for them. The relevant issue is probably [libinput#281](https://gitlab.freedesktop.org/libinput/libinput/issues/281) – so if you want to support it, be sure to go there.
