### ISSUE TITLE
Listen both L/R_Click when switching primary button

### ISSUE THREAD

**Issue by alex285** [elementary/switchboard-plug-mouse-touchpad#83]
I changed primary mouse button to R_Click, and then I had a bit hard time to switch back, because the L_Click was dead, and it wasnt straight obvious we should R_Click; Can we accept both Right & Left Click on this special case?

On a sidenote the pressed/active state isn't very clear, which was an additional reason I got confused

![mouse-settings](https://user-images.githubusercontent.com/11244308/61594040-cf99b000-abef-11e9-9b39-e116eae72e34.png)

**Comment by cassidyjames** [comment]
I suggested the accepting both primary and secondary clicks on Twitter since it would remedy this, but my one reservation is that it _could_ make it less immediately clear that the buttons just changed. But maybe being able to recover from accidental changes is worth it?

We could also color the selected button with `.accent` to help show it's selected, even if it already has the same pressed style as all other buttons; making it more clear isn't bad. :man_shrugging:

**Comment by alex285** [comment]
for reference, to add that GNOME does exactly that, it assigns both R&L press, which is a special case; it doesnt apply to other radio button selections

![Screenshot from 2019-07-23 16-07-09](https://user-images.githubusercontent.com/11244308/61714711-393acb00-ad64-11e9-8c1c-a2913a61788b.png)
